
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
 namespace RetractableLiftingSurface
 {
	static class Version
	{
		public const int major = 0;
		public const int minor = 1;
		public const int patch = 5;
		public const int build = 4;
		public const string Number = "0.1.5.4";
		public const string Text = Number + "/L Unofficial";
	}
}
